# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Time the room was booked for')),
                ('end_time', models.DateTimeField(verbose_name='Time the room was booked for')),
                ('booking_time', models.DateField(auto_now_add=True, verbose_name='Time the booking was made')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('booked_by', models.CharField(max_length=50, verbose_name='Booked by')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_image', models.FileField(upload_to='')),
                ('room_capacity', models.IntegerField()),
                ('room_fac', models.CharField(max_length=999, verbose_name='Room Facilities')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roombooker.Companies'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roombooker.Rooms'),
        ),
    ]
