# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roombooker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name_plural': 'rooms'},
        ),
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='end_minutes',
            field=models.FloatField(default=0, verbose_name='End Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='note',
            field=models.CharField(max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='start_minutes',
            field=models.FloatField(default=0, verbose_name='Start minute.'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='companies',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_notes',
            field=models.CharField(max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booked_by',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='end_time',
            field=models.IntegerField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start_time',
            field=models.IntegerField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(upload_to='roomimages'),
        ),
    ]
