# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooker', '0002_auto_20170314_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='end_minutes',
            field=models.FloatField(default=0, verbose_name='End Minutes'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='start_minutes',
            field=models.FloatField(default=0, verbose_name='Start minute.'),
        ),
    ]
