# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooker', '0002_auto_20170319_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='companies',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
    ]
