# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooker', '0003_auto_20170320_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
    ]
